# Generated by Django 6.0.5 on 2026-05-09 12:20

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('sport1', models.CharField(choices=[('Football', 'Football'), ('Tennis', 'Tennis'), ('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Hockey', 'Hockey'), ('Volleyball', 'Volleyball')], default='Football', max_length=10)),
                ('sport2', models.CharField(choices=[('Football', 'Football'), ('Tennis', 'Tennis'), ('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Hockey', 'Hockey'), ('Volleyball', 'Volleyball')], default='Football', max_length=10)),
                ('sport3', models.CharField(choices=[('Football', 'Football'), ('Tennis', 'Tennis'), ('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Hockey', 'Hockey'), ('Volleyball', 'Volleyball')], default='Football', max_length=10)),
                ('skill1', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=12)),
                ('skill2', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=12)),
                ('skill3', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=12)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SportVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('location', models.CharField(max_length=100, null=True, unique=True)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('sport', models.CharField(choices=[('Football', 'Football'), ('Tennis', 'Tennis'), ('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Hockey', 'Hockey'), ('Volleyball', 'Volleyball')], default='Football', max_length=10)),
                ('min_size', models.IntegerField(default=2)),
                ('max_size', models.IntegerField(default=10)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowUp2Move.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('location', models.CharField(max_length=100, null=True, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShowUp2Move.sportvenue')),
            ],
        ),
    ]
